name: Deploy to AWS
on:
    push:
      branches:
        - "main"
env:
    SHA: ${GITHUB_SHA}

permissions:
  id-token: write
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        steps:
          - uses: actions/checkout@v3

          - name: configure aws credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ vars.AWS_IAM_ROLE }}
              role-session-name: github-action
              aws-region: ${{ vars.AWS_REGION }}

          - name: ecr
            id: ecr
            uses: aws-actions/amazon-ecr-login@v1.6.0
            env:
              AWS_REGION: ${{ vars.AWS_REGION }}

          - uses: docker/metadata-action@v4
            id: metadata
            with:
                images: ${{ steps.ecr.outputs.registry }}/${{ vars.ECR_IMAGE_NAME }}
                tags: |
                    # minimal (short sha)
                    type=sha,prefix={{branch}}-,format=long

          - uses: int128/kaniko-action@v1
            with:
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }}
                cache: true
                cache-repository: ${{ steps.ecr.outputs.registry }}/${{ vars.ECR_IMAGE_NAME }}/cache





